import { ConsorcioParams } from '../types/consorcio';

export interface PresetProfile {
  id: string;
  title: string;
  category: ConsorcioParams['category'];
  description: string;
  badge: string;
  params: ConsorcioParams;
}

export const PRESET_PROFILES: PresetProfile[] = [
  {
    id: 'imovel-padrao',
    title: 'Imóvel / Apartamento',
    category: 'imovel',
    description: 'Carta ideal para aquisição de casa própria, terreno ou apartamento de médio padrão.',
    badge: 'Mais Popular',
    params: {
      category: 'imovel',
      creditValue: 350000,
      termMonths: 180,
      adminFeePercent: 16,
      reserveFundPercent: 2,
      insuranceMonthlyPercent: 0.035,
      annualReadjustmentRate: 4.5,
      readjustmentIndex: 'INCC',
      halfInstallmentUntilContemplation: false,
      reducedInstallmentPercent: 70,
      bidEnabled: true,
      bidMonth: 6,
      bidType: 'combinado',
      bidOwnResourcesPercent: 15,
      bidEmbeddedPercent: 20,
      postBidOption: 'reduce_installment',
      groupTotalMembers: 600,
      historicalAvgBidPercent: 35,
    },
  },
  {
    id: 'auto-suv',
    title: 'Carro Novo / SUV',
    category: 'auto',
    description: 'Para compra ou troca de veículo 0km sem entrada obrigatória e sem juros bancários.',
    badge: 'Rápida Contemplação',
    params: {
      category: 'auto',
      creditValue: 100000,
      termMonths: 72,
      adminFeePercent: 13,
      reserveFundPercent: 1.5,
      insuranceMonthlyPercent: 0.03,
      annualReadjustmentRate: 3.5,
      readjustmentIndex: 'IPCA',
      halfInstallmentUntilContemplation: false,
      reducedInstallmentPercent: 70,
      bidEnabled: true,
      bidMonth: 4,
      bidType: 'livre',
      bidOwnResourcesPercent: 30,
      bidEmbeddedPercent: 10,
      postBidOption: 'reduce_term',
      groupTotalMembers: 400,
      historicalAvgBidPercent: 42,
    },
  },
  {
    id: 'investimento-imobiliario',
    title: 'Investidor Imobiliário / Alavancagem',
    category: 'imovel',
    description: 'Estratégia de acumulação de patrimônio com crédito alavancado e lance agressivo.',
    badge: 'Alto Retorno',
    params: {
      category: 'imovel',
      creditValue: 700000,
      termMonths: 200,
      adminFeePercent: 15,
      reserveFundPercent: 2,
      insuranceMonthlyPercent: 0.038,
      annualReadjustmentRate: 4.0,
      readjustmentIndex: 'INCC',
      halfInstallmentUntilContemplation: true,
      reducedInstallmentPercent: 70,
      bidEnabled: true,
      bidMonth: 3,
      bidType: 'combinado',
      bidOwnResourcesPercent: 25,
      bidEmbeddedPercent: 25,
      postBidOption: 'reduce_installment',
      groupTotalMembers: 800,
      historicalAvgBidPercent: 45,
    },
  },
  {
    id: 'pesados-caminhao',
    title: 'Caminhão / Maquinário Agrícola',
    category: 'pesados',
    description: 'Renovação de frota ou aquisição de tratores com taxas administrativas reduzidas.',
    badge: 'Produtor & Frota',
    params: {
      category: 'pesados',
      creditValue: 500000,
      termMonths: 120,
      adminFeePercent: 12,
      reserveFundPercent: 1.5,
      insuranceMonthlyPercent: 0.04,
      annualReadjustmentRate: 4.0,
      readjustmentIndex: 'IPCA',
      halfInstallmentUntilContemplation: false,
      reducedInstallmentPercent: 75,
      bidEnabled: true,
      bidMonth: 6,
      bidType: 'livre',
      bidOwnResourcesPercent: 20,
      bidEmbeddedPercent: 15,
      postBidOption: 'reduce_installment',
      groupTotalMembers: 500,
      historicalAvgBidPercent: 36,
    },
  },
  {
    id: 'servicos-estudos-reforma',
    title: 'Serviços / Viagem / Cirurgia / Reforma',
    category: 'servicos',
    description: 'Cartas menores para projetos pessoais, pós-graduação, intercâmbio ou reformas.',
    badge: 'Flexível',
    params: {
      category: 'servicos',
      creditValue: 40000,
      termMonths: 36,
      adminFeePercent: 18,
      reserveFundPercent: 2,
      insuranceMonthlyPercent: 0.03,
      annualReadjustmentRate: 3.5,
      readjustmentIndex: 'IPCA',
      halfInstallmentUntilContemplation: false,
      reducedInstallmentPercent: 70,
      bidEnabled: false,
      bidMonth: 6,
      bidType: 'livre',
      bidOwnResourcesPercent: 0,
      bidEmbeddedPercent: 0,
      postBidOption: 'reduce_installment',
      groupTotalMembers: 300,
      historicalAvgBidPercent: 25,
    },
  },
];
